# !#/usr/bin/python2.7.12
# # Author: Karthika K   
# # Name: e29.py          
# # Date: 06-Nov-2017  
"""Description: How many distinct terms are in the sequence generated by a pow b for 2 <= a <= 100 and 2 <= b <= 100"""
power = []
for a in range(2, 101):
	for b in range(2,101):
		power.append(a ** b)
result = len(list(set(power)))
print result
